### ISSUE TITLE
ValueError when extracting mesh

### ISSUE THREAD

**Issue by AuthorityWang** [NVlabs/neuralangelo#13]
Hi, when I was extracting mesh from the checkpoint, I got a value error where the terminal output is as follows: 
```
(neuralangelo) vrlab@k8s-master-38:~/wangph1/workspace/neuralangelo$ CUDA_VISIBLE_DEVICES=2 torchrun --nproc_per_node=${GPUS} projects/neuralangelo/scripts/extract_mesh.py \
>     --logdir=logs/${GROUP}/${NAME} \
>     --config=${CONFIG} \
>     --checkpoint=${CHECKPOINT} \
>     --output_file=${OUTPUT_MESH} \
>     --resolution=${RESOLUTION} \
>     --block_res=${BLOCK_RES}
Running mesh extraction with 1 GPUs.
Make folder logs/example_group/example_name
Setup trainer.
Using random seed 0
model parameter count: 366,706,268
Initialize model weights using type: none, gain: None
Using random seed 0
Allow TensorFloat32 operations on supported devices
Loading checkpoint (local): logs/example_group/example_name/epoch_02857_iteration_000040000_checkpoint.pt
- Loading the model...
Done with loading the checkpoint.
Extracting surface at resolution 2048 2048 2048
vertices: 0
faces: 0
Traceback (most recent call last):
  File "projects/neuralangelo/scripts/extract_mesh.py", line 95, in <module>
    main()
  File "projects/neuralangelo/scripts/extract_mesh.py", line 90, in main
    mesh.vertices = mesh.vertices * meta["sphere_radius"] + np.array(meta["sphere_center"])
ValueError: operands could not be broadcast together with shapes (0,) (3,)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 502080) of binary: /home/vrlab/anaconda3/envs/neuralangelo/bin/python
Traceback (most recent call last):
  File "/home/vrlab/anaconda3/envs/neuralangelo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/vrlab/anaconda3/envs/neuralangelo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/vrlab/anaconda3/envs/neuralangelo/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/vrlab/anaconda3/envs/neuralangelo/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/vrlab/anaconda3/envs/neuralangelo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/vrlab/anaconda3/envs/neuralangelo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
projects/neuralangelo/scripts/extract_mesh.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-14_19:58:51
  host      : k8s-master-38
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 502080)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```
The server GPU used for extracting is a single RTX3090 with 24GB VRAM. 
I wonder if this is a bug or mistake made by myself. Thanks.

**Comment by mli0603** [comment]
Hi @AuthorityWang 

Thank you for your interest in the project.

The log suggests that there is no isosurface found in the SDF. Was the training successful? Have you checked the logged metrics?
```
Extracting surface at resolution 2048 2048 2048
vertices: 0
faces: 0
```

**Comment by BoMingZhao** [comment]
Hi @mli0603 
I have the same problem, I tried to view tensorboard but found the logs file is empty.
And my output is as follows:
```
Training with 1 GPUs.
Using random seed 0
Make folder logs/cambridge/KingsCollege
* checkpoint:
   * save_epoch: 9999999999
   * save_iter: 20000
   * save_latest_iter: 9999999999
   * save_period: 9999999999
   * strict_resume: True
* cudnn:
   * benchmark: True
   * deterministic: False
* data:
   * name: dummy
   * num_images: 1220
   * num_workers: 4
   * preload: True
   * readjust:
      * center: [0.0, 0.0, 0.0]
      * scale: 1.0
   * root: /mnt/nas_9/group/zhaoboming/datasets/PNeRFLoc/data_src/Cambridge/CambridgeLandmarks_Colmap_Retriangulated_1024px_neuralanglo/KingsCollege/dense
   * train:
      * batch_size: 2
      * image_size: [576, 1024]
      * subset: None
   * type: projects.neuralangelo.data
   * use_multi_epoch_loader: True
   * val:
      * batch_size: 2
      * image_size: [300, 533]
      * max_viz_samples: 16
      * subset: 4
* image_save_iter: 20000
* inference_args:
* local_rank: 0
* logdir: logs/cambridge/KingsCollege
* logging_iter: 100
* max_epoch: 9999999999
* max_iter: 500000
* metrics_epoch: None
* metrics_iter: None
* model:
   * appear_embed:
      * dim: 8
      * enabled: True
   * background:
      * enabled: True
      * encoding:
         * levels: 10
         * type: fourier
      * encoding_view:
         * levels: 3
         * type: spherical
      * mlp:
         * activ: relu
         * activ_density: softplus
         * activ_density_params:
         * activ_params:
         * hidden_dim: 256
         * hidden_dim_rgb: 128
         * num_layers: 8
         * num_layers_rgb: 2
         * skip: [4]
         * skip_rgb: []
      * view_dep: True
      * white: False
   * object:
      * rgb:
         * encoding_view:
            * levels: 3
            * type: spherical
         * mlp:
            * activ: relu_
            * activ_params:
            * hidden_dim: 256
            * num_layers: 4
            * skip: []
            * weight_norm: True
         * mode: idr
      * s_var:
         * anneal_end: 0.1
         * init_val: 3.0
      * sdf:
         * encoding:
            * coarse2fine:
               * enabled: True
               * init_active_level: 8
               * step: 5000
            * hashgrid:
               * dict_size: 22
               * dim: 8
               * max_logres: 11
               * min_logres: 5
               * range: [-2, 2]
            * levels: 16
            * type: hashgrid
         * gradient:
            * mode: numerical
            * taps: 4
         * mlp:
            * activ: softplus
            * activ_params:
               * beta: 100
            * geometric_init: True
            * hidden_dim: 256
            * inside_out: False
            * num_layers: 2
            * out_bias: 0.5
            * skip: []
            * weight_norm: True
   * render:
      * num_sample_hierarchy: 4
      * num_samples:
         * background: 32
         * coarse: 64
         * fine: 16
      * rand_rays: 512
      * stratified: True
   * type: projects.neuralangelo.model
* nvtx_profile: False
* optim:
   * fused_opt: False
   * params:
      * lr: 0.001
      * weight_decay: 0.001
   * sched:
      * gamma: 10.0
      * iteration_mode: True
      * step_size: 9999999999
      * two_steps: [300000, 400000]
      * type: two_steps_with_warmup
      * warm_up_end: 5000
   * type: AdamW
* pretrained_weight: None
* source_filename: projects/neuralangelo/configs/custom/KingsCollege.yaml
* speed_benchmark: False
* test_data:
   * name: dummy
   * num_workers: 0
   * test:
      * batch_size: 1
      * is_lmdb: False
      * roots: None
   * type: imaginaire.datasets.images
* timeout_period: 9999999
* trainer:
   * amp_config:
      * backoff_factor: 0.5
      * enabled: False
      * growth_factor: 2.0
      * growth_interval: 2000
      * init_scale: 65536.0
   * ddp_config:
      * find_unused_parameters: False
      * static_graph: True
   * depth_vis_scale: 0.5
   * ema_config:
      * beta: 0.9999
      * enabled: False
      * load_ema_checkpoint: False
      * start_iteration: 0
   * grad_accum_iter: 1
   * image_to_tensorboard: False
   * init:
      * gain: None
      * type: none
   * loss_weight:
      * curvature: 0.0005
      * eikonal: 0.1
      * render: 1.0
   * type: projects.neuralangelo.trainer
* validation_iter: 5000
* wandb_image_iter: 10000
* wandb_scalar_iter: 100
cudnn benchmark: True
cudnn deterministic: False
Setup trainer.
Using random seed 0
model parameter count: 366,725,324
Initialize model weights using type: none, gain: None
Using random seed 0
Allow TensorFloat32 operations on supported devices
```

**Comment by mli0603** [comment]
Hi @BoMingZhao 

Do you mean you have the same issue when extracting the mesh, i.e., the vertices and triangles are 0?

**Comment by BoMingZhao** [comment]
> triangles are 0

Yes. However, it is my own bug. I found that the image HW stored in the images folder is not aligned with the intrinsic parameters of colmap. Now I extract the mesh on 20000 iter, but it still looks unreasonable. I would like to know why the tensorboard file is empty, and whether Neuralangelo takes a long time to converge. Thank you very much!

![1692038493477](https://github.com/NVlabs/neuralangelo/assets/26064261/9f7f676a-a40b-4b4a-8813-367465695413)

**Comment by chenhsuanlin** [comment]
Hi @BoMingZhao, please see #4 for discussions on runtime. The visualization tool we support is Weights and Biases. We currently don't support Tensorboard visualizations. The created `tensorboard` directory is deprecated (will push a fix to remove that), but please feel free to submit a PR to add TB support!

**Comment by mli0603** [comment]
Hi @BoMingZhao 

It shouldn't take long to get the coarse shape. Otherwise, there is probably something wrong during the pre-processing/capturing. I recommend you monitor the normal map logged in wandb. You can turn on wanb logging by `--wanb` when you run the code.
