### ISSUE TITLE
Colab Demo Broken

### ISSUE THREAD

**Issue by kommanderpi** [NVlabs/neuralangelo#189]
When installing colmap in colab there seems to be an issue that results in this:

/content/neuralangelo
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-69b86f843e97>](https://localhost:8080/#) in <cell line: 12>()
     10 # Import imaginaire modules.
     11 from projects.nerf.utils import camera, visualize
---> 12 from third_party.colmap.scripts.python.read_write_model import read_model
     13 # Read the COLMAP data.
     14 cameras, images, points_3D = read_model(path=f"{colmap_path}/sparse", ext=".bin")

ModuleNotFoundError: No module named 'third_party.colmap'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by lexvandersluijs** [comment]
I'm also experiencing that the Colab demo is broken, with a different set of error messages:

```
frame=  100 fps=0.0 q=2.0 Lsize=N/A time=00:00:07.96 bitrate=N/A speed=  25x    
video:7275kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
colmap: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
colmap: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
colmap: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
cp: cannot stat 'datasets/lego_ds2/sparse/0/*.bin': No such file or directory
projects/neuralangelo/scripts/run_colmap.sh: line 34: [: too many arguments
colmap: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py", line 226, in <module>
    data_to_json(args)
  File "/content/neuralangelo/projects/neuralangelo/scripts/convert_data_to_json.py", line 191, in data_to_json
    cameras, images, points3D = read_model(os.path.join(args.data_dir, "sparse"), ext=".bin")
  File "/content/neuralangelo/third_party/colmap/scripts/python/read_write_model.py", line 435, in read_model
    cameras = read_cameras_binary(os.path.join(path, "cameras" + ext))
  File "/content/neuralangelo/third_party/colmap/scripts/python/read_write_model.py", line 134, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/lego_ds2/sparse/cameras.bin'
Traceback (most recent call last):
  File "/content/neuralangelo/projects/neuralangelo/scripts/generate_config.py", line 83, in <module>
    generate_config(args)
  File "/content/neuralangelo/projects/neuralangelo/scripts/generate_config.py", line 30, in generate_config
    num_images = len(os.listdir(os.path.join(args.data_dir, "images")))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/lego_ds2/images'
```

**Comment by RIP-tommy** [comment]
I edited 2nd cell like below.

`# @title { vertical-output: true }
%cd /content
!apt-get install \
    ninja-build \
    build-essential \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-system-dev \
    libeigen3-dev \
    libflann-dev \
    libfreeimage-dev \
    libmetis-dev \
    libgoogle-glog-dev \
    libgtest-dev \
    libsqlite3-dev \
    libglew-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    libceres-dev \
    nvidia-cuda-toolkit
!apt-get install xvfb
# libglvnd is needed for COLMAP to run on Google Colab (https://github.com/colmap/colmap/issues/1271#issuecomment-931900582)
!git clone https://github.com/NVIDIA/libglvnd
%cd /content/libglvnd
!apt-get install libxext-dev libx11-dev x11proto-gl-dev
!apt-get install autoconf automake libtool
!apt-get install libffi-dev
!./autogen.sh
!./configure
!make -j4
!make install
# Download and extract the pre-compiled COLMAP library
%cd /content
!gdown 1Ob2pSUFp46lZNAEK7y7ZSnpwvdIMsILb
!tar -C /usr -zxf colmap-3.8.tar.gz
# Install other Python libraries for the data preparation scripts
!pip install \
    addict \
    k3d \
    opencv-python-headless \
    pillow \
    plotly \
    pyyaml \
    trimesh
`

**Comment by WB-tommy** [comment]
I added "nvidia-cuda-toolkit" package when 'sudo apt-get install' in 2nd cell
