### ISSUE TITLE
`RuntimeError: cannot reshape tensor of 0 elements into shape [2, 512, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous`

### ISSUE THREAD

**Issue by satyajitghana** [NVlabs/neuralangelo#3]
```
root@beast2:/opt/data# torchrun --nproc_per_node=${GPUS} train.py     --logdir=logs/${GROUP}/${NAME}     --config=${CONFIG}     --show_pbar
Training with 1 GPUs.
Using random seed 0
Make folder logs/example_group/example_name
* checkpoint:
   * save_epoch: 9999999999
   * save_iter: 20000
   * save_latest_iter: 9999999999
   * save_period: 9999999999
   * strict_resume: True
* cudnn:
   * benchmark: True
   * deterministic: False
* data:
   * name: dummy
   * num_images: 117
   * num_workers: 4
   * preload: True
   * readjust:
      * center: [0.0, 0.0, 0.0]
      * scale: 1.0
   * root: IMG_6088_skip12/dense
   * train:
      * batch_size: 2
      * image_size: [1079, 1923]
      * subset: None
   * type: projects.neuralangelo.data
   * use_multi_epoch_loader: True
   * val:
      * batch_size: 2
      * image_size: [300, 534]
      * max_viz_samples: 16
      * subset: 4
* image_save_iter: 9999999999
* inference_args:
* local_rank: 0
* logdir: logs/example_group/example_name
* logging_iter: 9999999999999
* max_epoch: 9999999999
* max_iter: 500000
* metrics_epoch: None
* metrics_iter: None
* model:
   * appear_embed:
      * dim: 8
      * enabled: True
   * background:
      * encoding:
         * levels: 10
         * type: fourier
      * encoding_view:
         * levels: 3
         * type: spherical
      * mlp:
         * activ: relu
         * activ_density: softplus
         * activ_density_params:
         * activ_params:
         * hidden_dim: 256
         * hidden_dim_rgb: 128
         * num_layers: 8
         * num_layers_rgb: 2
         * skip: [4]
         * skip_rgb: []
      * view_dep: True
      * white: False
   * object:
      * rgb:
         * encoding_view:
            * levels: 3
            * type: spherical
         * mlp:
            * activ: relu_
            * activ_params:
            * hidden_dim: 256
            * num_layers: 4
            * skip: []
            * weight_norm: True
         * mode: idr
      * s_var:
         * anneal_end: 0.1
         * init_val: 3.0
      * sdf:
         * encoding:
            * coarse2fine:
               * enabled: True
               * init_active_level: 8
               * step: 5000
            * hashgrid:
               * dict_size: 22
               * dim: 8
               * max_logres: 11
               * min_logres: 5
               * range: [-2, 2]
            * levels: 16
            * type: hashgrid
         * gradient:
            * mode: numerical
            * taps: 4
         * mlp:
            * activ: softplus
            * activ_params:
               * beta: 100
            * geometric_init: True
            * hidden_dim: 256
            * inside_out: True
            * num_layers: 2
            * out_bias: 0.5
            * skip: []
            * weight_norm: True
   * render:
      * num_sample_hierarchy: 4
      * num_samples:
         * background: 0
         * coarse: 64
         * fine: 16
      * rand_rays: 512
      * stratified: True
   * type: projects.neuralangelo.model
* nvtx_profile: False
* optim:
   * fused_opt: False
   * params:
      * lr: 0.001
      * weight_decay: 0.001
   * sched:
      * gamma: 10.0
      * iteration_mode: True
      * step_size: 9999999999
      * two_steps: [300000, 400000]
      * type: two_steps_with_warmup
      * warm_up_end: 5000
   * type: AdamW
* pretrained_weight: None
* source_filename: projects/neuralangelo/configs/custom/toy_example.yaml
* speed_benchmark: False
* test_data:
   * name: dummy
   * num_workers: 0
   * test:
      * batch_size: 1
      * is_lmdb: False
      * roots: None
   * type: imaginaire.datasets.images
* timeout_period: 9999999
* trainer:
   * amp_config:
      * backoff_factor: 0.5
      * enabled: False
      * growth_factor: 2.0
      * growth_interval: 2000
      * init_scale: 65536.0
   * ddp_config:
      * find_unused_parameters: False
      * static_graph: True
   * depth_vis_scale: 0.5
   * ema_config:
      * beta: 0.9999
      * enabled: False
      * load_ema_checkpoint: False
      * start_iteration: 0
   * grad_accum_iter: 1
   * image_to_tensorboard: False
   * init:
      * gain: None
      * type: none
   * loss_weight:
      * curvature: 0.0005
      * eikonal: 0.1
      * render: 1.0
   * type: projects.neuralangelo.trainer
* validation_iter: 5000
* wandb_image_iter: 10000
* wandb_scalar_iter: 100
cudnn benchmark: True
cudnn deterministic: False
Setup trainer.
Using random seed 0
model parameter count: 366,707,676
Initialize model weights using type: none, gain: None
Using random seed 0
Allow TensorFloat32 operations on supported devices
Train dataset length: 117                                                                                                       
Val dataset length: 4                                                                                                           
Training from scratch.
Initialize wandb
Traceback (most recent call last):                                                                                              
  File "train.py", line 104, in <module>
    main()
  File "train.py", line 93, in main
    trainer.train(cfg,
  File "/opt/data/projects/neuralangelo/trainer.py", line 106, in train
    super().train(cfg, data_loader, single_gpu, profile, show_pbar)
  File "/opt/data/projects/nerf/trainers/base.py", line 109, in train
    data_all = self.test(self.eval_data_loader, mode="val", show_pbar=show_pbar)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/projects/nerf/trainers/base.py", line 138, in test
    output = model.inference(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/data/projects/neuralangelo/model.py", line 70, in inference
    output = self.render_image(data["pose"], data["intr"], image_size=self.image_size_val,
  File "/opt/data/projects/neuralangelo/model.py", line 96, in render_image
    output_batch = self.render_rays(center, ray_unit, sample_idx=sample_idx, stratified=stratified)
  File "/opt/data/projects/neuralangelo/model.py", line 122, in render_rays
    output_background = self.render_rays_background(center, ray_unit, far, app_outside, stratified=stratified)
  File "/opt/data/projects/neuralangelo/model.py", line 185, in render_rays_background
    rgbs, densities = self.background_nerf.forward(points, rays_unit, app_outside)  # [B,R,N,3]
  File "/opt/data/projects/neuralangelo/utils/modules.py", line 271, in forward
    points_enc = self.encode(points_3D)  # [...,4+LD]
  File "/opt/data/projects/neuralangelo/utils/modules.py", line 297, in encode
    points_enc = nerf_util.positional_encoding(points, num_freq_bases=self.cfg_background.encoding.levels)
  File "/opt/data/projects/nerf/utils/nerf_util.py", line 146, in positional_encoding
    input_enc = input_enc.view(*input.shape[:-1], -1)  # [B,...,2NL].
RuntimeError: cannot reshape tensor of 0 elements into shape [2, 512, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 796) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+fe05266', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-12_08:09:34
  host      : beast2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 796)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
root@beast2:/opt/data# 

```

**Comment by satyajitghana** [comment]
I am using the latest docker

Also

consider adding package versions to `requirements.txt` also don't add opencv-python and opencv-python-headless together.

**Comment by chenhsuanlin** [comment]
Thanks for the issue, this is indeed a bug -- will push a fix soon.

**Comment by chenhsuanlin** [comment]
Just pushed a fix (754d51f2c) to `main`, please let me know if this fixes your issue.

**Comment by satyajitghana** [comment]
It training now!

uses about 20GB of VRAM on a RTX3090

![image](https://github.com/NVlabs/neuralangelo/assets/8092481/8cedaee5-daf9-4879-93ee-097808430ec5)

![image](https://github.com/NVlabs/neuralangelo/assets/8092481/2d1fd89b-c63e-40f6-a9ac-0538e586071a)

**Comment by chenhsuanlin** [comment]
Awesome, glad it's working again!
