### ISSUE TITLE
Isosurface extraction error (ubuntu18.04)

### ISSUE THREAD

**Issue by mowangmodi** [NVlabs/neuralangelo#30]
Here are the issues I reported as errors, how can I solve them?

torchrun --nproc_per_node=2 projects/neuralangelo/scripts/extract_mesh.py --logdir=logs/example_group_dtu24/dtu_24 --config=projects/neuralangelo/configs/dtu.yaml --checkpoint=logs/example_group_dtu24/dtu_24/epoch_01600_iteration_000040000_checkpoint.pt --output_file=dtu_24_40000.ply --resolution=2048 --block_res=128
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "projects/neuralangelo/scripts/extract_mesh.py", line 25, in <module>
    from projects.neuralangelo.utils.mesh import extract_mesh  # noqa: E402
  File "/home/ubuntu/Desktop/modi/neuralangelo-main/projects/neuralangelo/utils/mesh.py", line 15, in <module>
    import mcubes
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/mcubes/__init__.py", line 4, in <module>
    from .smoothing import smooth, smooth_constrained, smooth_gaussian
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/mcubes/smoothing.py", line 11, in <module>
    from scipy import sparse
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 283, in <module>
    from . import csgraph
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/__init__.py", line 120, in <module>
    from ._isolve import *
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 6, in <module>
    from .lgmres import lgmres
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/lgmres.py", line 7, in <module>
    from scipy.linalg import get_blas_funcs
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/__init__.py", line 209, in <module>
    from ._matfuncs import *
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs.py", line 19, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "projects/neuralangelo/scripts/extract_mesh.py", line 25, in <module>
    from projects.neuralangelo.utils.mesh import extract_mesh  # noqa: E402
  File "/home/ubuntu/Desktop/modi/neuralangelo-main/projects/neuralangelo/utils/mesh.py", line 15, in <module>
    import mcubes
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/mcubes/__init__.py", line 4, in <module>
    from .smoothing import smooth, smooth_constrained, smooth_gaussian
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/mcubes/smoothing.py", line 11, in <module>
    from scipy import sparse
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/__init__.py", line 200, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 283, in <module>
    from . import csgraph
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/csgraph/__init__.py", line 185, in <module>
    from ._laplacian import laplacian
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/csgraph/_laplacian.py", line 7, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/__init__.py", line 120, in <module>
    from ._isolve import *
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/__init__.py", line 6, in <module>
    from .lgmres import lgmres
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/sparse/linalg/_isolve/lgmres.py", line 7, in <module>
    from scipy.linalg import get_blas_funcs
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/__init__.py", line 209, in <module>
    from ._matfuncs import *
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs.py", line 19, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5037) of binary: /home/ubuntu/anaconda3/envs/nelo/bin/python3.8
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nelo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
projects/neuralangelo/scripts/extract_mesh.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-17_11:15:59
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 5038)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-17_11:15:59
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5037)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by chenhsuanlin** [comment]
Has the paths of any conda library files changed by any chance? Looking at this line
```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.26' not found (required by /home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)
```
it looks like it's trying to read `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`, which is not in your conda environment.

**Comment by JuliusQv** [comment]
For this error:
 `ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.26' not found (required by /home/ubuntu/anaconda3/envs/nelo/lib/python3.8/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-38-x86_64-linux-gnu.so)`
try this command in your conda env:
 `conda install -c anaconda scipy==1.9.1 `

**Comment by GDbbq** [comment]
https://chat3.fastgpt.me/#:~:text=You%20can%20use%20the%20official%20provided%20Docker%20environment.

**Comment by GDbbq** [comment]
You can use the official provided Docker environment

**Comment by Bai426** [comment]
Change --resolution=2048 to 1024, --block_res=128 to 64

**Comment by chenhsuanlin** [comment]
Closing due to inactivity, please feel free to reopen if the issue persists.

**Comment by YangLI-aftermath** [comment]
Try changing the version of Scipy. 1.10.0 resolved my error.
