### ISSUE TITLE
data preparation error

### ISSUE THREAD

**Issue by chongxian** [NVlabs/neuralangelo#53]
I use the wsl2 and ubuntu22.04，and cuda11.8，and use the conda the create envs. when I use the `EXPERIMENT_NAME=toy_example
PATH_TO_VIDEO=toy_example.MOV
SKIP_FRAME_RATE=24
SCENE_TYPE=object  # {outdoor,indoor,object}
bash projects/neuralangelo/scripts/preprocess.sh ${EXPERIMENT_NAME} ${PATH_TO_VIDEO} ${SKIP_FRAME_RATE} ${SCENE_TYPE}`, it report errors.

 **[swscaler @ 0x5628e034efc0] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to 'datasets/toy_example_skip24/raw_images/%06d.jpg':
  Metadata:
    major_brand     : qt
    minor_version   : 512
    compatible_brands: qt
    encoder         : Lavf58.76.100
  Stream #0:0: Video: mjpeg, yuvj420p(pc, progressive), 800x800 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 25 fps, 25 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : FFMP
      encoder         : Lavc58.134.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    9 fps=0.0 q=2.0 Lsize=N/A time=00:00:07.72 bitrate=N/A speed=42.5x
video:649kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

*** Aborted at 1692614036 (unix time) try "date -d @1692614036" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x272f) received by PID 10031 (TID 0x7f0d05dbd080) from PID 10031; stack trace: ***
    @     0x7f0d0b968046 (unknown)
    @     0x7f0d09c10520 (unknown)
    @     0x7f0d09c64a7c pthread_kill
    @     0x7f0d09c10476 raise
    @     0x7f0d09bf67f3 abort
    @     0x7f0d0a205ba3 QMessageLogger::fatal()
    @     0x7f0d0a80c713 QGuiApplicationPrivate::createPlatformIntegration()
    @     0x7f0d0a80cc08 QGuiApplicationPrivate::createEventDispatcher()
    @     0x7f0d0a435b17 QCoreApplicationPrivate::init()
    @     0x7f0d0a80fb70 QGuiApplicationPrivate::init()
    @     0x7f0d0af23ced QApplicationPrivate::init()
    @     0x55f19813a3dd colmap::RunFeatureExtractor()
    @     0x55f19812c499 main
    @     0x7f0d09bf7d90 (unknown)
    @     0x7f0d09bf7e40 __libc_start_main
    @     0x55f19812f3e5 _start
projects/neuralangelo/scripts/run_colmap.sh: line 22: 10031 Aborted                 colmap feature_extractor --database_path ${1}/database.db --image_path ${1}/raw_images --ImageReader.camera_model=RADIAL --SiftExtraction.use_gpu=true --SiftExtraction.num_threads=32 --ImageReader.single_camera=true
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

*** Aborted at 1692614036 (unix time) try "date -d @1692614036" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x2730) received by PID 10032 (TID 0x7f243bbcc080) from PID 10032; stack trace: ***
    @     0x7f2441777046 (unknown)
    @     0x7f243fa1f520 (unknown)
    @     0x7f243fa73a7c pthread_kill
    @     0x7f243fa1f476 raise
    @     0x7f243fa057f3 abort
    @     0x7f2440014ba3 QMessageLogger::fatal()
    @     0x7f244061b713 QGuiApplicationPrivate::createPlatformIntegration()
    @     0x7f244061bc08 QGuiApplicationPrivate::createEventDispatcher()
    @     0x7f2440244b17 QCoreApplicationPrivate::init()
    @     0x7f244061eb70 QGuiApplicationPrivate::init()
    @     0x7f2440d32ced QApplicationPrivate::init()
    @     0x560626178e76 colmap::RunSequentialMatcher()
    @     0x56062616d499 main
    @     0x7f243fa06d90 (unknown)
    @     0x7f243fa06e40 __libc_start_main
    @     0x5606261703e5 _start
projects/neuralangelo/scripts/run_colmap.sh: line 26: 10032 Aborted                 colmap sequential_matcher --database_path ${1}/database.db --SiftMatching.use_gpu=true

==============================================================================
Loading database
==============================================================================

Loading cameras... 0 in 0.001s
Loading matches... 0 in 0.000s
Loading images... 0 in 0.001s (connected 0)
Building correspondence graph... in 0.000s (ignored 0)

Elapsed time: 0.000 [minutes]

WARNING: No images with matches found in the database.

ERROR: failed to create sparse model

==============================================================================
Reading reconstruction
==============================================================================

F0821 18:33:57.171896 10035 reconstruction.cc:745] cameras, images, points3D files do not exist at datasets/toy_example_skip24/sparse/0
*** Check failure stack trace: ***
    @     0x7fc87b025b03  google::LogMessage::Fail()
    @     0x7fc87b02d9d1  google::LogMessage::SendToLog()
    @     0x7fc87b0257c2  google::LogMessage::Flush()
    @     0x7fc87b02778f  google::LogMessageFatal::~LogMessageFatal()
    @     0x55843ac4e6f2  colmap::Reconstruction::Read()
    @     0x55843aba787a  colmap::RunImageUndistorter()
    @     0x55843ab91499  main
    @     0x7fc8792c1d90  (unknown)
    @     0x7fc8792c1e40  __libc_start_main
    @     0x55843ab943e5  _start
projects/neuralangelo/scripts/run_colmap.sh: line 38: 10035 Aborted                 colmap image_undistorter --image_path ${1}/raw_images --input_path ${1}/sparse/0 --output_path ${1}/dense --output_type COLMAP --max_image_size 2000
Traceback (most recent call last):
  File "projects/neuralangelo/scripts/convert_data_to_json.py", line 199, in <module>
    auto_bound(args)
  File "projects/neuralangelo/scripts/convert_data_to_json.py", line 161, in auto_bound
    cameras, images, points3D = read_model(os.path.join(args.data_dir, "sparse"), ext=".bin")
  File "/mnt/f/xbruanProject/neuralangelo/third_party/colmap/scripts/python/read_write_model.py", line 435, in read_model
    cameras = read_cameras_binary(os.path.join(path, "cameras" + ext))
  File "/mnt/f/xbruanProject/neuralangelo/third_party/colmap/scripts/python/read_write_model.py", line 134, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/toy_example_skip24/dense/sparse/cameras.bin'
Traceback (most recent call last):
  File "projects/neuralangelo/scripts/generate_config.py", line 81, in <module>
    generate_config(args)
  File "projects/neuralangelo/scripts/generate_config.py", line 30, in generate_config
    num_images = len(os.listdir(os.path.join(args.data_dir, "images")))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/toy_example_skip24/dense/images'**

**Comment by chenhsuanlin** [comment]
Hi @chongxian, it seems that COLMAP was not properly installed (specifically Qt). How are you installing COLMAP with conda? The recommended way would be to either use our prebuilt Docker image or follow the installation instructions in the [official documentation](https://colmap.github.io/install.html).

**Comment by chenhsuanlin** [comment]
Closing due to inactivity, please feel free to reopen if the issue persists.
