### ISSUE TITLE
Mesh extraction failure: data loader keeps quitting unexpectedly

### ISSUE THREAD

**Issue by smandava98** [NVlabs/neuralangelo#60]
Hello,
I am running the code on an A10 GPU. The training process for Neuralangelo works fine and I am trying to run the mesh extraction. However, I keep getting this:
```
Done with loading the checkpoint.
Extracting surface at resolution 520 764 1028
  0%|                                                                                                                        | 0/270 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2493) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
```

I looked at the OOM FAQ section but I don't know how to fix this kind of issue for the mesh extraction step. It also seems to be complaining about shared memory and not CUDA memory. I have a feeling this is related to the Docker container but I looked up how to resolve it and I am not sure which route to take. Let me know if there is a solution for this that is recommended!

**Comment by smandava98** [comment]
Fixed the error.
Had to rerun the docker container with a higher shm size.

docker run --shm-size=50G <other options like -it, -v, etc.> <image name>
